// Filesystem project store. Projects + generated assets live under
// public/generated/<projectId>/ so the dev server can serve them directly.

import { promises as fs } from "fs";
import path from "path";
import { Project } from "./types";

const ROOT = path.join(process.cwd(), "public", "generated");

export function projectDir(id: string): string {
  // Defensive: ids are generated by us, but never allow traversal.
  if (!/^[a-z0-9-]+$/i.test(id)) throw new Error("Invalid project id");
  return path.join(ROOT, id);
}

export async function listProjects(): Promise<Project[]> {
  try {
    const entries = await fs.readdir(ROOT, { withFileTypes: true });
    const projects: Project[] = [];
    for (const e of entries) {
      if (!e.isDirectory()) continue;
      try {
        const raw = await fs.readFile(
          path.join(ROOT, e.name, "project.json"),
          "utf-8"
        );
        projects.push(JSON.parse(raw));
      } catch {
        // skip dirs without project.json
      }
    }
    return projects.sort((a, b) => b.updatedAt.localeCompare(a.updatedAt));
  } catch {
    return [];
  }
}

export async function loadProject(id: string): Promise<Project | null> {
  try {
    const raw = await fs.readFile(
      path.join(projectDir(id), "project.json"),
      "utf-8"
    );
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

export async function saveProject(project: Project): Promise<void> {
  const dir = projectDir(project.id);
  await fs.mkdir(dir, { recursive: true });
  project.updatedAt = new Date().toISOString();
  await fs.writeFile(
    path.join(dir, "project.json"),
    JSON.stringify(project, null, 2),
    "utf-8"
  );
}

export async function saveAsset(
  projectId: string,
  relPath: string,
  bytes: Buffer
): Promise<string> {
  const dir = projectDir(projectId);
  const full = path.join(dir, relPath);
  if (!full.startsWith(dir)) throw new Error("Invalid asset path");
  await fs.mkdir(path.dirname(full), { recursive: true });
  await fs.writeFile(full, bytes);
  // Public URL path
  return `/generated/${projectId}/${relPath.replace(/\\/g, "/")}`;
}

export async function deleteProject(id: string): Promise<void> {
  await fs.rm(projectDir(id), { recursive: true, force: true });
}
